# $NetBSD$

PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
DISTNAME=	jsonlines-1.2.0
CATEGORIES=	textproc python
MASTER_SITES=   ${MASTER_SITE_PYPI:=j/jsonlines/}

COMMENT=	A Python library to simplify working with jsonlines and ndjson data
MAINTAINER=	pkgsrc@fluentdevelopment.com.au
LICENSE=	modified-bsd

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
