# $NetBSD$

DISTNAME=	god-0.13.7
CATEGORIES=	sysutils

MAINTAINER=	pkgsrc@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/gollum/gollum/wiki
COMMENT=	An easy to configure, easy to extend monitoring framework written in Ruby
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
