# $NetBSD$

DISTNAME=	rouge-2.2.1
CATEGORIES=	www

MAINTAINER=	pkgsrc@fluentdevelopment.com.au
HOMEPAGE=	http://rouge.jneen.net/
COMMENT=	Pure-ruby colorizer based on pygments
LICENSE=	mit

RUBYGEM_OPTIONS+=	--format-executable

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
