# $NetBSD$
#

DISTNAME=	hashie-3.5.7
PKGNAME=        ${RUBY_PKGPREFIX}-${DISTNAME:S/hashie/hashie35/}
CATEGORIES=	misc

MAINTAINER=	pkgsrc@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/intridea/hashie
COMMENT=	Small collection of tools that make hashes more powerful

LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
