# $NetBSD: Makefile,v 1.85 2019/08/15 08:06:29 adam Exp $

DISTNAME=	nginx-1.16.1
FLUENTREVISION=	1
PKGNAME=	${DISTNAME:C/$/fd${FLUENTREVISION}/}

MAINTAINER=	pkgsrc@fluentdevelopment.com.au

.include "../../fluent/nginx/Makefile.common"
