# $NetBSD: Makefile,v 1.79 2018/08/24 18:27:07 adam Exp $

DISTNAME=	nginx-1.14.0
PKGREVISION=	2
FLUENTREVISION=	1
PKGNAME=	${DISTNAME:C/$/fd${FLUENTREVISION}/}

MAINTAINER=	pkgsrc@fluentdevelopment.com.au

.include "../../fluent/nginx/Makefile.common"
