# $NetBSD: Makefile,v 1.82 2019/03/27 06:45:13 adam Exp $

DISTNAME=	nginx-1.14.2
PKGREVISION=	1

FLUENTREVISION=	1
PKGNAME=	${DISTNAME:C/$/fd${FLUENTREVISION}/}

MAINTAINER=	pkgsrc@fluentdevelopment.com.au

.include "../../fluent/nginx/Makefile.common"
