# $NetBSD$

DISTNAME=	github-markdown-0.6.9
CATEGORIES=	textproc

MAINTAINER=	pkgsrc@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/github/markup
COMMENT=	Self-contained Markdown parser for GitHub - NOT MAINTAINED OR SUPPORTED
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
