# $NetBSD$

DISTNAME=	arel-6.0.4
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME:C/(-[0-9])/6\1/}
CATEGORIES=	databases

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://github.com/rails/arel
COMMENT=	Arel is a SQL AST manager for Ruby
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
