# $NetBSD$

DISTNAME=	jwt-1.5.6
CATEGORIES=	security

MAINTAINER=	pkgsrc@fluentdevelopment.com.au
HOMEPAGE=	http://github.com/jwt/ruby-jwt
COMMENT=	A pure ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
