# $NetBSD$

DISTNAME=	multi_xml-0.6.0
CATEGORIES=	textproc

MAINTAINER=	timshel@fluentdevelopment.com.au
HOMEPAGE=	https://github.com/sferik/multi_xml
COMMENT=	Provides swappable XML backends utilizing LibXML, Nokogiri, Ox, or REXML
LICENSE=	mit

RUBY_RDOC_REQD=	3.0

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
